name: nabihni
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  provider: ^6.0.4
  # UI Libraries
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  table_calendar: ^3.1.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Image handling
  image_picker: ^1.0.7

  # Firebase packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Add splash screen tool here
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#009788"
  image: assets/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/med.png
    - assets/pill.png
    - assets/profile.jpg
    - assets/doctor.jpg
    - assets/empty.png
    - assets/medical-checkup.png
    - assets/splash.png
