name: nabihni
description: "A new Flutter project."
publish_to: 'none' # احذف السطر ده لو ناوي تنشر على pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # مكتبات الواجهة (UI)
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  table_calendar: ^3.1.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # إضافات الصور
  image_picker: ^1.0.7

  # باكدجات Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/med.png
    - assets/pill.png
    - assets/profile.jpg
    - assets/doctor.jpg
