// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeodt8df1akevOmoxF5YcaLWPo0fFAX_Q',
    appId: '1:48056569605:web:56d4f196d4a25601e4316c',
    messagingSenderId: '48056569605',
    projectId: 'nabehni-app',
    authDomain: 'nabehni-app.firebaseapp.com',
    storageBucket: 'nabehni-app.firebasestorage.app',
    measurementId: 'G-6NNC7DL7GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6WiN_q0_MAv3s5VzErvBODcNMO3W5NaU',
    appId: '1:48056569605:android:3d94688ffbe89893e4316c',
    messagingSenderId: '48056569605',
    projectId: 'nabehni-app',
    storageBucket: 'nabehni-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPFFg0YJSkAE7sZbvKrx0yJB4tHotl9fo',
    appId: '1:48056569605:ios:825bc3b5512fb7a5e4316c',
    messagingSenderId: '48056569605',
    projectId: 'nabehni-app',
    storageBucket: 'nabehni-app.firebasestorage.app',
    iosBundleId: 'com.example.nabihni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPFFg0YJSkAE7sZbvKrx0yJB4tHotl9fo',
    appId: '1:48056569605:ios:825bc3b5512fb7a5e4316c',
    messagingSenderId: '48056569605',
    projectId: 'nabehni-app',
    storageBucket: 'nabehni-app.firebasestorage.app',
    iosBundleId: 'com.example.nabihni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeodt8df1akevOmoxF5YcaLWPo0fFAX_Q',
    appId: '1:48056569605:web:558a6998d4c2875ee4316c',
    messagingSenderId: '48056569605',
    projectId: 'nabehni-app',
    authDomain: 'nabehni-app.firebaseapp.com',
    storageBucket: 'nabehni-app.firebasestorage.app',
    measurementId: 'G-E01R56P7VL',
  );
}
